trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/
    exclude:
    - infrastructure/README.md

variables:
  vmImageName: 'ubuntu-latest'
  resource_group: 'chirps'
  service_connection: resources-chirps-dev-sc
  location: westeurope
  

steps:

- checkout: self

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create Storage Account
  inputs:
    ConnectedServiceName: $(service_connection)
    resourceGroupName: $(resource_group)
    location: $(location)
    csmFile: infrastructure/storage.json