apiVersion : apps/v1
kind: Deployment
metadata:
  name: chirps 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chirps
  template:
    metadata:
      labels:
        app: chirps 
    spec:
      containers:
        - name: chirps 
          image: webserverdevacr001.azurecr.io/chirps
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
      imagePullSecrets:
        - name: acr-secret