trigger:
  branches:
    include:
    - master
  paths:
    include:
    - app/
    - infrastructure/build-and-push.yaml
    - Dockerfile
    exclude:
    - app/README.md

resources:
- repo: self

variables:
  service_connection: chirps-sc
  resource_group: webserver-dev-rg
  cluster: webserver-dev-aks
  registry: webserverdevacr
  registry_url: webserverdevacr.azurecr.io
  registry_repo: chirps
  image_tag: $(Build.BuildId)

steps:
- task: AzureCLI@2
  displayName: Build and push image
  inputs:
    azureSubscription: $(service_connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # ACR_PASSWORD=$(az acr credential show -n $(registry) --query "passwords[0].value")
      # az acr login --username $(registry) --password $ACR_PASSWORD
      az acr login -n $(registry)
      docker build \
          -t $(registry_url)/$(registry_repo):$(image_tag) \
          -t $(registry_url)/$(registry_repo):latest \
          .
      docker push $(registry_url)/$(registry_repo) --all-tags

- task: AzureCLI@2
  displayName: Deploy new image
  inputs:
    azureSubscription: $(service_connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials --resource-group $(resource_group) --name $(cluster) 
      kubectl apply -f manifests --namespace chirps
      kubectl rollout restart deployment chirps --namespace chirps
