trigger:
  branches:
    include:
    - master
  paths:
    include:
    - infrastructure/deploy.yaml
    - manifests/

resources:
- repo: self

variables:
  service_connection: chirps-sc
  resource_group: webserver-dev-rg
  cluster: webserver-dev-aks

steps:
- task: AzureCLI@2
  displayName: Deploy new image
  inputs:
    azureSubscription: $(service_connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials --resource-group $(resource_group) --name $(cluster) 
      kubectl apply -f manifests --namespace chirps