name: Build, push and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  RESOURCE_GROUP: webserver-dev-rg
  CLUSTER: webserver-dev-aks
  REGISTRY: webserverdevacr
  REGISTRY_URL: webserverdevacr.azurecr.io
  REGISTRY_REPO: chirps
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Build and push image
        run: |
          az acr login -n $REGISTRY
          docker build \
            -t $REGISTRY_URL/$REGISTRY_REPO:github$GITHUB_RUN_NUMBER \
            -t $REGISTRY_URL/$REGISTRY_REPO:latest \
            .
          docker push $REGISTRY_URL/$REGISTRY_REPO --all-tags

      - name: Deploy new image
        run: |
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER 
          kubectl apply -f manifests --namespace chirps
          kubectl rollout restart deployment chirps --namespace chirps